[package]
name = "gauss-svg"
version.workspace = true
edition.workspace = true

[features]
test-support = ["gauss-core/test-support"]

[dependencies]
gauss-core = { path = "../gauss-core" }
roxmltree = "0.21.1"
slotmap = "1.1.1"
thiserror = "2.0.18"

[dev-dependencies]
gauss-core = { path = "../gauss-core", features = ["test-support"] }
rstest = "0.26.1"

[lints]
workspace = true
