[package]
name = "gauss-svg"
version.workspace = true
edition.workspace = true

[features]
test-support = ["gauss-core/test-support"]

[dependencies]
gauss-core = { version = "0.1.0", path = "../gauss-core" }
roxmltree = "0.21.1"
slotmap = "1.1.1"
thiserror = "2.0.18"

[dev-dependencies]
camino = "1.1.9"
cap-std = { version = "3.4.2", features = ["fs_utf8"] }
gauss-core = { version = "0.1.0", path = "../gauss-core", features = ["test-support"] }
rstest = "0.26.1"
rstest-bdd = "0.6.0-beta3"
rstest-bdd-macros = "0.6.0-beta3"
test_support = { version = "0.1.0", path = "../test_support" }

[lints]
workspace = true
