[package]
name = "gauss-core"
version.workspace = true
edition.workspace = true

[features]
test-support = []

[dependencies]
slotmap = "1.1.1"
thiserror = "2.0.18"
undo_2 = "0.2.1"

[dev-dependencies]
gauss-core = { path = ".", features = ["test-support"] }
rstest = { workspace = true }
rstest-bdd = { workspace = true }
rstest-bdd-macros = { workspace = true }
test_support = { version = "0.1.0", path = "../test_support" }

[lints]
workspace = true
